version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: asset_mongo
    ports:
      - "27015:27015"
    volumes:
      - mongo-data:/data/db
    command: ["mongod", "--port", "27015"]

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: asset
    depends_on:
      - mongo
    environment:
      - MONGO_URI=${MONGO_URI}
    ports:
      - "8080:8080"
    volumes:
      - ./asset_http_go:/server_asset

volumes:
  mongo-data:
