version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: game_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    command: ["mongod", "--port", "27017"]
    networks:
      - game-map-network

  udp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: game_udp
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://localhost:27017 # 환경 변수를 직접 설정합니다.
    ports:
      - "8050:8050/udp"
    volumes:
      - ./game_udp_go:/server_game
    stdin_open: true
    tty: true
    networks:
      - game-map-network

  http:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: game_http
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://localhost:27017 # 환경 변수를 직접 설정합니다.
    ports:
      - "8060:8060"
    volumes:
      - ./game_http_go:/server_game
    stdin_open: true
    tty: true
    networks:
      - game-map-network

volumes:
  mongo-data:

networks:
  game-map-network:
    external: true